TEMP="temp"
cd $TEMP

IDCOMUNIDAD=( '01' '02' '03' '04' '05' '06' '07' '08' '09' '10' '11' '12' '13' '14' '15' '16' '17' '18' '19' )
COMUNIDADES=( 'ANDALUCIA' 'ARAGON' 'ASTURIAS' 'BALEARES' 'CANARIAS' 'CANTABRIA' 'CASTILLALEON' 'CASTILLALAMANCHA' 'CATALUNA' 'COMUNITATVALENCIANA' 'EXTREMADURA' 'GALICIA' 'MADRID' 'MURCIA' 'NAVARRA' 'PAISVASCO' 'LARIOJA' 'CEUTA' 'MELILLA' )
IDPROVINCIA=('01')
PROVINCIAS=('ALAVA' 'ALBACETE' 'ALICANTE' 'ALMERIA' 'AVILA' 'BADAJOZ' 'BALEARES' 'BARCELONA' 'BURGOS' 'CACERES' 'CADIZ' 'CASTELLON' 'CIUDADREAL' 'CORDOBA' 'LACORU' 'CUENCA' 'GIRONA' 'GRANADA' 'GUADALAJARA' 'GUIPUZCOA' 'HUELVA' 'HUESCA' 'JAEN' 'LEON' 'LLEIDA' 'LARIOJA' 'LUGO' 'MADRID' 'MALAGA' 'MURCIA' 'NAVARRA' 'ORENSE' 'ASTURIAS' 'PALENCIA' 'LASPALMAS' 'PONTEVEDRA' 'SALAMANCA' 'TENERIFE' 'CANTABRIA' 'SEGOVIA' 'SEVILLA' 'SORIA' 'TARRAGONA' 'TERUEL' 'TOLEDO' 'VALENCIA' 'VALLADOLID' 'VIZCAYA' 'ZAMORA' 'ZARAGOZA' 'CEUTA' 'MELILLA')
TYPES=( 'NUCLEAR' 'CARBONES' 'LIGNITOS' 'FUEL' 'GAS' 'OTRO' 'TOTAL' )

for FILE in $(ls *.txt)
do
    FILENAME=$(echo ${FILE} | cut -f 1 -d '.')
    for PROVINCIA in ${PROVINCIAS[@]}
    do
        DATA=($(grep ${PROVINCIA} ${FILE}))
        for k in ${!TYPES[@]}
        do
            VALUE=$(echo ${DATA[k+1]} | sed 's/\.//g' )
            echo "${FILENAME}  ${VALUE}" >> "${PROVINCIA}_${TYPES[k]}.txt"
        done
    done
done
